/* eslint-disable @typescript-eslint/naming-convention */
export const viewsData = ["Day", "Week", "Month"];
const today = new Date();

export const doctorsData = [
  {
    title: "Nembo Lukeni",
    Gender: "Male",
    Text: "NemboLukni",
    Id: 1,
    imgURL:
      "https://ej2.syncfusion.com/showcase/angular/appointmentplanner/assets/images/NemboLukni.png",
    DepartmentId: 1,
    Color: "#ea7a57",
    Education: "MBBS, DMRD",
    Specialization: "General Medicine",
    Experience: "10+ years",
    Designation: "Senior Specialist",
    DutyTiming: "Shift1",
    Email: "nembo36@sample.com",
    Mobile: "(206) 555-9482",
    Availability: "busy",
    StartHour: "08:00",
    EndHour: "17:00",
    AvailableDays: [0, 2, 3, 4, 5],
    WorkDays: [
      {
        Day: "Sunday",
        Index: 0,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 1, 8, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 1, 17, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 1, 12, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 1, 13, 0),
        State: "AddBreak",
      },
      {
        Day: "Monday",
        Index: 1,
        Enable: false,
        WorkStartHour: new Date(today.getFullYear(), 5, 2, 8, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 2, 17, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 2, 12, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 2, 13, 0),
        State: "TimeOff",
      },
      {
        Day: "Tuesday",
        Index: 2,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 3, 8, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 3, 17, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 3, 12, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 3, 13, 0),
        State: "AddBreak",
      },
      {
        Day: "Wednesday",
        Index: 3,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 4, 8, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 4, 17, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 4, 12, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 4, 13, 0),
        State: "AddBreak",
      },
      {
        Day: "Thursday",
        Index: 4,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 5, 8, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 5, 17, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 5, 12, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 5, 13, 0),
        State: "AddBreak",
      },
      {
        Day: "Friday",
        Index: 5,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 6, 8, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 6, 17, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 6, 12, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 6, 13, 0),
        State: "RemoveBreak",
      },
      {
        Day: "Saturday",
        Index: 6,
        Enable: false,
        WorkStartHour: new Date(today.getFullYear(), 5, 7, 8, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 7, 17, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 7, 12, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 7, 13, 0),
        State: "TimeOff",
      },
    ],
  },
  {
    title: "Mollie Cobb",
    Gender: "Female",
    Text: "MollieCobb",
    Id: 2,
    imgURL:
      "https://ej2.syncfusion.com/showcase/angular/appointmentplanner/assets/images/MollieCobb.png",
    DepartmentId: 2,
    Color: "#7fa900",
    Education: "MBBS, MD PAEDIATRICS, DM NEUROLOGY",
    Specialization: "Neurology",
    Experience: "2+ years",
    Designation: "Junior Specialist",
    Email: "mollie65@rpy.com",
    DutyTiming: "Shift2",
    Mobile: "(206) 555-3412",
    Availability: "available",
    StartHour: "10:00",
    EndHour: "19:00",
    AvailableDays: [0, 1, 2, 3, 4],
    WorkDays: [
      {
        Day: "Sunday",
        Index: 0,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 1, 10, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 1, 19, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 1, 14, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 1, 15, 0),
        State: "AddBreak",
      },
      {
        Day: "Monday",
        Index: 1,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 2, 10, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 2, 19, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 2, 14, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 2, 15, 0),
        State: "RemoveBreak",
      },
      {
        Day: "Tuesday",
        Index: 2,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 3, 10, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 3, 19, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 3, 14, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 3, 15, 0),
        State: "AddBreak",
      },
      {
        Day: "Wednesday",
        Index: 3,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 4, 10, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 4, 19, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 4, 14, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 4, 15, 0),
        State: "AddBreak",
      },
      {
        Day: "Thursday",
        Index: 4,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 5, 10, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 5, 19, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 5, 14, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 5, 15, 0),
        State: "RemoveBreak",
      },
      {
        Day: "Friday",
        Index: 5,
        Enable: false,
        WorkStartHour: new Date(today.getFullYear(), 5, 6, 10, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 6, 19, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 6, 14, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 6, 15, 0),
        State: "TimeOff",
      },
      {
        Day: "Saturday",
        Index: 6,
        Enable: false,
        WorkStartHour: new Date(today.getFullYear(), 5, 7, 10, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 7, 19, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 7, 14, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 7, 15, 0),
        State: "TimeOff",
      },
    ],
  },
  {
    title: "Yara Barros",
    Gender: "Female",
    Text: "YaraBarros",
    Id: 3,
    imgURL:
      "https://ej2.syncfusion.com/showcase/angular/appointmentplanner/assets/images/YaraBarros.png",
    DepartmentId: 1,
    Color: "#fec200",
    Education: "MBBS, DNB (FAMILY MEDICINE)",
    Specialization: "General Medicine",
    Experience: "8+ years",
    Designation: "Senior Specialist",
    DutyTiming: "Shift3",
    Email: "yara105@sample.com",
    Mobile: "(206) 555-8122",
    Availability: "away",
    StartHour: "12:00",
    EndHour: "21:00",
    AvailableDays: [1, 2, 3, 4, 5],
    WorkDays: [
      {
        Day: "Sunday",
        Index: 0,
        Enable: false,
        WorkStartHour: new Date(today.getFullYear(), 5, 1, 12, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 1, 21, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 1, 16, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 1, 17, 0),
        State: "TimeOff",
      },
      {
        Day: "Monday",
        Index: 1,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 2, 12, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 2, 21, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 2, 16, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 2, 17, 0),
        State: "AddBreak",
      },
      {
        Day: "Tuesday",
        Index: 2,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 3, 12, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 3, 21, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 3, 16, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 3, 17, 0),
        State: "AddBreak",
      },
      {
        Day: "Wednesday",
        Index: 3,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 4, 12, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 4, 21, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 4, 16, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 4, 17, 0),
        State: "AddBreak",
      },
      {
        Day: "Thursday",
        Index: 4,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 5, 12, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 5, 21, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 5, 16, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 5, 17, 0),
        State: "AddBreak",
      },
      {
        Day: "Friday",
        Index: 5,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 6, 12, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 6, 21, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 6, 16, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 6, 17, 0),
        State: "RemoveBreak",
      },
      {
        Day: "Saturday",
        Index: 6,
        Enable: false,
        WorkStartHour: new Date(today.getFullYear(), 5, 7, 12, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 7, 21, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 7, 16, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 7, 17, 0),
        State: "TimeOff",
      },
    ],
  },
  {
    title: "Paul Walker",
    Gender: "Male",
    Text: "PaulWalker",
    Id: 4,
    imgURL:
      "https://ej2.syncfusion.com/showcase/angular/appointmentplanner/assets/images/PaulWalker.png",
    DepartmentId: 3,
    Color: "#865fcf",
    Education: "MBBS, MD (Dermatology)",
    Designation: "Senior Dermatology",
    Specialization: "Dermatology",
    Experience: "10+ years",
    DutyTiming: "Shift1",
    Email: "paul39@mail.com",
    Mobile: "(717) 555-4848",
    Availability: "busy",
    StartHour: "08:00",
    EndHour: "17:00",
    AvailableDays: [2, 3, 4, 5, 6],
    WorkDays: [
      {
        Day: "Sunday",
        Index: 0,
        Enable: false,
        WorkStartHour: new Date(today.getFullYear(), 5, 1, 8, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 1, 17, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 1, 12, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 1, 13, 0),
        State: "TimeOff",
      },
      {
        Day: "Monday",
        Index: 1,
        Enable: false,
        WorkStartHour: new Date(today.getFullYear(), 5, 2, 8, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 2, 17, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 2, 12, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 2, 13, 0),
        State: "TimeOff",
      },
      {
        Day: "Tuesday",
        Index: 2,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 3, 8, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 3, 17, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 3, 12, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 3, 13, 0),
        State: "AddBreak",
      },
      {
        Day: "Wednesday",
        Index: 3,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 4, 8, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 4, 17, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 4, 12, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 4, 13, 0),
        State: "AddBreak",
      },
      {
        Day: "Thursday",
        Index: 4,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 5, 8, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 5, 17, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 5, 12, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 5, 13, 0),
        State: "AddBreak",
      },
      {
        Day: "Friday",
        Index: 5,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 6, 8, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 6, 17, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 6, 12, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 6, 13, 0),
        State: "RemoveBreak",
      },
      {
        Day: "Saturday",
        Index: 6,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 7, 8, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 7, 17, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 7, 12, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 7, 13, 0),
        State: "AddBreak",
      },
    ],
  },
  {
    title: "Amelia Edwards",
    Gender: "Female",
    Text: "AmeliaEdwards",
    Id: 5,
    imgURL:
      "https://ej2.syncfusion.com/showcase/angular/appointmentplanner/assets/images/AmeliaEdwards.png",
    DepartmentId: 4,
    Color: "#1aaa55",
    Education: "MBBS, MD",
    Designation: "Senior Orthopedics",
    Specialization: "Orthopedics",
    Experience: "10+ years",
    DutyTiming: "Shift2",
    Email: "amelia101@rpy.com",
    Mobile: "(717) 555-7773",
    Availability: "available",
    StartHour: "10:00",
    EndHour: "19:00",
    AvailableDays: [0, 2, 3, 4, 5],
    WorkDays: [
      {
        Day: "Sunday",
        Index: 0,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 1, 10, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 1, 19, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 1, 14, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 1, 15, 0),
        State: "AddBreak",
      },
      {
        Day: "Monday",
        Index: 1,
        Enable: false,
        WorkStartHour: new Date(today.getFullYear(), 5, 2, 10, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 2, 19, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 2, 14, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 2, 15, 0),
        State: "TimeOff",
      },
      {
        Day: "Tuesday",
        Index: 2,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 3, 10, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 3, 19, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 3, 14, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 3, 15, 0),
        State: "AddBreak",
      },
      {
        Day: "Wednesday",
        Index: 3,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 4, 10, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 4, 19, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 4, 14, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 4, 15, 0),
        State: "AddBreak",
      },
      {
        Day: "Thursday",
        Index: 4,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 5, 10, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 5, 19, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 5, 14, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 5, 15, 0),
        State: "AddBreak",
      },
      {
        Day: "Friday",
        Index: 5,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 6, 10, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 6, 19, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 6, 14, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 6, 15, 0),
        State: "RemoveBreak",
      },
      {
        Day: "Saturday",
        Index: 6,
        Enable: false,
        WorkStartHour: new Date(today.getFullYear(), 5, 7, 10, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 7, 19, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 7, 14, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 7, 15, 0),
        State: "TimeOff",
      },
    ],
  },
  {
    title: "Alexa Richardson",
    Gender: "Female",
    Text: "AlexaRichardson",
    Id: 6,
    imgURL:
      "https://ej2.syncfusion.com/showcase/angular/appointmentplanner/assets/images/AlexaRichardson.png",
    DepartmentId: 5,
    Color: "#df5286",
    Education: "MD, DM, FACC, FICC",
    Designation: "Practitioner",
    Specialization: "Dialectology",
    Experience: "1+ years",
    DutyTiming: "Shift2",
    Email: "alexa55@sample.com",
    Mobile: "(717) 555-5598",
    Availability: "busy",
    StartHour: "10:00",
    EndHour: "19:00",
    AvailableDays: [2, 3, 4, 5, 6],
    WorkDays: [
      {
        Day: "Sunday",
        Index: 0,
        Enable: false,
        WorkStartHour: new Date(today.getFullYear(), 5, 1, 10, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 1, 19, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 1, 14, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 1, 15, 0),
        State: "TimeOff",
      },
      {
        Day: "Monday",
        Index: 1,
        Enable: false,
        WorkStartHour: new Date(today.getFullYear(), 5, 2, 10, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 2, 19, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 2, 14, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 2, 15, 0),
        State: "TimeOff",
      },
      {
        Day: "Tuesday",
        Index: 2,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 3, 10, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 3, 19, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 3, 14, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 3, 15, 0),
        State: "AddBreak",
      },
      {
        Day: "Wednesday",
        Index: 3,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 4, 10, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 4, 19, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 4, 14, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 4, 15, 0),
        State: "AddBreak",
      },
      {
        Day: "Thursday",
        Index: 4,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 5, 10, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 5, 19, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 5, 14, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 5, 15, 0),
        State: "AddBreak",
      },
      {
        Day: "Friday",
        Index: 5,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 6, 10, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 6, 19, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 6, 14, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 6, 15, 0),
        State: "RemoveBreak",
      },
      {
        Day: "Saturday",
        Index: 6,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 7, 10, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 7, 19, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 7, 14, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 7, 15, 0),
        State: "AddBreak",
      },
    ],
  },
  {
    title: "Nout Golstein",
    Gender: "Male",
    Text: "NoutGolstein",
    Id: 7,
    imgURL:
      "https://ej2.syncfusion.com/showcase/angular/appointmentplanner/assets/images/NoutGolstein.png",
    DepartmentId: 6,
    Color: "#00bdae",
    Education: "MS",
    Designation: "Junior Cardiologist",
    Specialization: "Cardiology",
    Experience: "2+ years",
    DutyTiming: "Shift3",
    Email: "nout49@rpy.com",
    Mobile: "(206) 555-1189",
    Availability: "busy",
    StartHour: "12:00",
    EndHour: "21:00",
    AvailableDays: [0, 3, 4, 5, 6],
    WorkDays: [
      {
        Day: "Sunday",
        Index: 0,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 1, 12, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 1, 21, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 1, 16, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 1, 17, 0),
        State: "AddBreak",
      },
      {
        Day: "Monday",
        Index: 1,
        Enable: false,
        WorkStartHour: new Date(today.getFullYear(), 5, 2, 12, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 2, 21, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 2, 16, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 2, 17, 0),
        State: "TimeOff",
      },
      {
        Day: "Tuesday",
        Index: 2,
        Enable: false,
        WorkStartHour: new Date(today.getFullYear(), 5, 3, 12, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 3, 21, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 3, 16, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 3, 17, 0),
        State: "TimeOff",
      },
      {
        Day: "Wednesday",
        Index: 3,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 4, 12, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 4, 21, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 4, 16, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 4, 17, 0),
        State: "AddBreak",
      },
      {
        Day: "Thursday",
        Index: 4,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 5, 12, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 5, 21, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 5, 16, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 5, 17, 0),
        State: "AddBreak",
      },
      {
        Day: "Friday",
        Index: 5,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 6, 12, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 6, 21, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 6, 16, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 6, 17, 0),
        State: "RemoveBreak",
      },
      {
        Day: "Saturday",
        Index: 6,
        Enable: true,
        WorkStartHour: new Date(today.getFullYear(), 5, 7, 12, 0),
        WorkEndHour: new Date(today.getFullYear(), 5, 7, 21, 0),
        BreakStartHour: new Date(today.getFullYear(), 5, 7, 16, 0),
        BreakEndHour: new Date(today.getFullYear(), 5, 7, 17, 0),
        State: "AddBreak",
      },
    ],
  },
];

export const patientsData = [
  {
    Id: 1,
    title: "Laura",
    Text: "Laura",
    DOB: new Date(1980, 8, 3),
    Mobile: "(717) 555-4444",
    Email: "laura90@mail.com",
    Address: "507 - 20th Ave. E.\r\nApt. 2A",
    Disease: "Eye Checkup",
    DoctorName: "",
    DepartmentName: "General Medicine",
    BloodGroup: "O+",
    Gender: "Female",
    Symptoms: "Sweating, Chills and Shivering",
  },
  {
    Id: 2,
    title: "Milka",
    Text: "Milka",
    DOB: new Date(2000, 3, 5),
    Mobile: "(717) 555-4445",
    Email: "milka40@sample.com",
    Address: "908 W. Capital Way",
    Disease: "Bone Fracture",
    DoctorName: "",
    DepartmentName: "Orthopedics",
    BloodGroup: "AB+",
    Gender: "Female",
    Symptoms: "Swelling or bruising over a bone, Pain in the injured area",
  },
  {
    Id: 3,
    title: "Adams",
    Text: "Adams",
    DOB: new Date(1985, 2, 3),
    Mobile: "(717) 555-4454",
    Email: "adams89@rpy.com",
    Address: "722 Moss Bay Blvd.",
    Disease: "Eye and Spectactles",
    DoctorName: "",
    DepartmentName: "General Medicine",
    BloodGroup: "B+",
    Gender: "Male",
    Symptoms: "Frequent squinting, Eye fatigue or strain",
  },
  {
    Id: 4,
    title: "Janet",
    Text: "Janet",
    DOB: new Date(2000, 7, 3),
    Mobile: "(717) 555-4544",
    Email: "janet79@rpy.com",
    Address: "4110 Old Redmond Rd.",
    Disease: "Biological Problem",
    DoctorName: "",
    DepartmentName: "General Medicine",
    BloodGroup: "B+",
    Gender: "Male",
    Symptoms: "Physical aches or pain, Memory difficulties",
  },
  {
    Id: 5,
    title: "Mercy",
    Text: "Mercy",
    DOB: new Date(2005, 4, 29),
    Mobile: "(717) 555-5444",
    Email: "mercy60@sample.com",
    Address: "14 Garrett Hill",
    Disease: "Skin Hives",
    DoctorName: "",
    DepartmentName: "Dermatology",
    BloodGroup: "AB-",
    Gender: "Female",
    Symptoms: "Outbreak of swollen, pale red bumps or plaques",
  },
  {
    Id: 6,
    title: "Richa",
    Text: "Richa",
    DOB: new Date(1989, 10, 29),
    Mobile: "(206) 555-4444",
    Email: "richa46@mail.com",
    Address: "Coventry House\r\nMiner Rd.",
    Disease: "Arm Fracture",
    DoctorName: "",
    DepartmentName: "Orthopedics",
    BloodGroup: "B+",
    Gender: "Female",
    Symptoms: "Swelling, warmth, or redness in the joint",
  },
  {
    Id: 7,
    title: "Maud Oliver",
    Text: "MaudOliver",
    DOB: new Date(1989, 10, 29),
    Mobile: "(206) 666-4444",
    Email: "moud46@rpy.com",
    Address: "Coventry House\r\nMiner Rd.",
    Disease: "Racing heartbeat",
    DoctorName: "",
    DepartmentName: "Cardiology",
    BloodGroup: "B+",
    Gender: "Male",
    Symptoms: "A fluttering in your chest",
  },
];

export const waitingList = [
  {
    Id: 1,
    title: "Laura",
    start: new Date(today.getFullYear(), 5, 3, 8, 30),
    end: new Date(today.getFullYear(), 5, 3, 9, 30),
    Disease: "Sudden loss of vision",
    DoctorName: "",
    DepartmentName: "General Medicine",
    Treatment: "CHECKUP",
    DepartmentId: 1,
    PatientId: 1,
  },
  {
    Id: 2,
    title: "Milka",
    start: new Date(today.getFullYear(), 5, 4, 8, 30),
    end: new Date(today.getFullYear(), 5, 4, 10, 30),
    Disease: "Bone Fracture",
    DoctorName: "",
    DepartmentName: "Orthopedics",
    Treatment: "SURGERY",
    DepartmentId: 4,
    PatientId: 2,
  },
  {
    Id: 3,
    title: "Adams",
    start: new Date(today.getFullYear(), 5, 4, 9, 30),
    end: new Date(today.getFullYear(), 5, 4, 10, 30),
    Disease: "Skin Hives",
    DoctorName: "",
    DepartmentName: "Dermatology",
    Treatment: "CHECKUP",
    DepartmentId: 3,
    PatientId: 3,
  },
  {
    Id: 4,
    title: "Janet",
    start: new Date(today.getFullYear(), 5, 3, 11, 0),
    end: new Date(today.getFullYear(), 5, 3, 12, 30),
    Disease: "Frequent urination",
    DoctorName: "",
    DepartmentName: "Dialectology",
    Treatment: "DIALOGIS",
    DepartmentId: 5,
    PatientId: 4,
  },
  {
    Id: 5,
    title: "Mercy",
    start: new Date(today.getFullYear(), 5, 3, 11, 0),
    end: new Date(today.getFullYear(), 5, 3, 12, 30),
    Disease: "Muscle weakness",
    DoctorName: "",
    DepartmentName: "Neurology",
    Treatment: "DIAGNOSIS",
    DepartmentId: 2,
    PatientId: 5,
  },
  {
    Id: 6,
    title: "Richa",
    start: new Date(today.getFullYear(), 5, 3, 11, 0),
    end: new Date(today.getFullYear(), 5, 3, 12, 30),
    Disease: "Shortness of breath",
    DoctorName: "",
    DepartmentName: "Cardiology",
    Treatment: "REGULAR CHECKUP",
    DepartmentId: 6,
    PatientId: 6,
  },
  {
    Id: 7,
    title: "Richa",
    start: new Date(today.getFullYear(), 5, 3, 8, 30),
    end: new Date(today.getFullYear(), 5, 3, 9, 30),
    Disease: "Sudden loss of vision",
    DoctorName: "",
    DepartmentName: "General Medicine",
    Treatment: "CHECKUP",
    DepartmentId: 1,
    PatientId: 6,
  },
  {
    Id: 8,
    title: "Mercy",
    start: new Date(today.getFullYear(), 5, 4, 8, 30),
    end: new Date(today.getFullYear(), 5, 4, 10, 30),
    Disease: "Bone Fracture",
    DoctorName: "",
    DepartmentName: "Orthopedics",
    Treatment: "SURGERY",
    DepartmentId: 4,
    PatientId: 5,
  },
  {
    Id: 9,
    title: "Janet",
    start: new Date(today.getFullYear(), 5, 4, 9, 30),
    end: new Date(today.getFullYear(), 5, 4, 10, 30),
    Disease: "Skin Hives",
    DoctorName: "",
    DepartmentName: "Dermatology",
    Treatment: "CHECKUP",
    DepartmentId: 3,
    PatientId: 4,
  },
];

export const hospitalData = [
  {
    Id: 1000,
    title: "Milka",
    start: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 1,
      10,
      30
    ),
    end: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 1,
      11,
      30
    ),
    Disease: "Bone Fracture",
    DoctorName: "Mollie Cobb",
    DepartmentName: "Orthopedics",
    DepartmentId: 4,
    DoctorId: 5,
    PatientId: 2,
    Symptoms: "Swelling or bruising over a bone",
  },
  {
    Id: 1001,
    title: "Janet",
    start: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate(),
      11,
      0
    ),
    end: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate(),
      12,
      0
    ),
    Disease: "Biological Problems",
    DoctorName: "Nembo Lukeni",
    DepartmentName: "Diabetology",
    DepartmentId: 1,
    DoctorId: 3,
    PatientId: 4,
    Symptoms: "Physical aches or pain, Memory difficulties",
  },
  {
    Id: 1002,
    title: "Mercy",
    Disease: "Skin Problem",
    DoctorName: "Yara Barros",
    DepartmentName: "Dermatology",
    DepartmentId: 3,
    start: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 5,
      10,
      0
    ),
    end: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 5,
      11,
      0
    ),
    DoctorId: 4,
    PatientId: 5,
    Symptoms: "outbreak of swollen, pale red bumps",
  },
  {
    Id: 1003,
    title: "Laura",
    Disease: "Feeling very hungry - even though you are eating",
    DoctorName: "Mollie Cobb",
    DepartmentName: "Diabetology",
    DepartmentId: 5,
    start: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 10,
      10,
      0
    ),
    end: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 10,
      11,
      0
    ),
    DoctorId: 6,
    PatientId: 1,
    Symptoms: "Urinating often, Extreme fatigue",
  },
  {
    Id: 1004,
    title: "Richa",
    Disease: "Skin care treatment",
    DoctorName: "Yara Barros",
    DepartmentName: "Dermatology",
    DepartmentId: 3,
    start: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() - 3,
      10,
      0
    ),
    end: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() - 3,
      11,
      0
    ),
    DoctorId: 4,
    PatientId: 2,
    Symptoms: "Scaly or rough skin, Peeling skin",
  },
  {
    Id: 1005,
    title: "Adams",
    Disease: "General Checkup",
    DoctorName: "Nembo Lukeni",
    DepartmentName: "General Medicine",
    DepartmentId: 1,
    start: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 5,
      13,
      30
    ),
    end: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 5,
      14,
      0
    ),
    DoctorId: 1,
    PatientId: 3,
    Symptoms: "Decreased energy, Chronic fatigue",
  },
  {
    Id: 1006,
    title: "Richa",
    Disease: "Left Arm Fracture",
    DoctorName: "Paul Walker",
    DepartmentName: "Orthopedics",
    DepartmentId: 4,
    start: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 7,
      16,
      0
    ),
    end: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 7,
      17,
      0
    ),
    DoctorId: 5,
    PatientId: 6,
    Symptoms: "Swelling, warmth, or redness",
  },
  {
    Id: 1007,
    title: "Adams",
    Disease: "Chest Pain",
    DoctorName: "Amelia Edwards",
    DepartmentName: "Cardiology",
    DepartmentId: 6,
    start: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() - 7,
      11,
      0
    ),
    end: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() - 7,
      11,
      30
    ),
    DoctorId: 7,
    PatientId: 2,
    Symptoms: "Shortness of breath, Swollen feet",
  },
  {
    Id: 1008,
    title: "Milka",
    Disease: "Skin Care Treatment",
    DoctorName: "Mollie Cobb",
    DepartmentName: "Dermatology",
    DepartmentId: 3,
    start: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate(),
      9,
      0
    ),
    end: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate(),
      10,
      0
    ),
    DoctorId: 4,
    PatientId: 2,
    Symptoms: "a rash, which might be painful",
  },
  {
    Id: 1009,
    title: "Adams",
    Disease: "Surgery Treatment",
    DoctorName: "Mollie Cobb",
    DepartmentName: "General Medicine",
    DepartmentId: 1,
    start: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 12,
      14,
      0
    ),
    end: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 12,
      16,
      0
    ),
    DoctorId: 1,
    PatientId: 3,
    Symptoms: "Pain at Site, Swelling/Hardening",
  },
  {
    Id: 1010,
    title: "Adams",
    Disease: "Bone Problem",
    DoctorName: "Paul Walker",
    DepartmentName: "Orthopedics",
    DepartmentId: 4,
    start: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 11,
      11,
      0
    ),
    end: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 11,
      13,
      0
    ),
    DoctorId: 5,
    PatientId: 3,
    Symptoms: "Recurring or constant joint pain",
  },
  {
    Id: 1011,
    title: "Adams",
    Disease: "General Checkup",
    DoctorName: "Nembo Lukeni",
    DepartmentName: "General Medicine",
    DepartmentId: 1,
    start: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 9,
      11,
      0
    ),
    end: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 9,
      12,
      0
    ),
    DoctorId: 1,
    PatientId: 3,
    Symptoms: "a pulsating feeling in the head",
  },
  {
    Id: 1012,
    title: "Janet",
    Disease: "Complete loss of sensation",
    DoctorName: "Yara Barros",
    DepartmentName: "Neurology",
    DepartmentId: 2,
    start: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 11,
      16,
      30
    ),
    end: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 11,
      17,
      30
    ),
    DoctorId: 2,
    PatientId: 4,
    Symptoms: "Partial or complete paralysis",
  },
  {
    Id: 1013,
    title: "Laura",
    start: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 15,
      13,
      0
    ),
    end: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 15,
      14,
      0
    ),
    Disease: "Health Checkup",
    DoctorName: "Mollie Cobb",
    DepartmentName: "General Medicine",
    DepartmentId: 1,
    DoctorId: 1,
    PatientId: 1,
    Symptoms: "Sweating, Chills and Shivering",
  },
  {
    Id: 1014,
    title: "Adams",
    start: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() - 6,
      16,
      0
    ),
    end: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() - 6,
      17,
      0
    ),
    Disease: "Eye and Spectacles Checkup",
    DoctorName: "Nembo Lukeni",
    DepartmentName: "General Medicine",
    DepartmentId: 1,
    DoctorId: 3,
    PatientId: 3,
    Symptoms: "Frequent squinting, Eye fatigue",
  },
  {
    Id: 1015,
    title: "Milka",
    Disease: "Feeling hungry after eating",
    DoctorName: "Paul Walker",
    DepartmentName: "Diabetology",
    DepartmentId: 5,
    start: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() - 4,
      12,
      0
    ),
    end: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() - 4,
      13,
      0
    ),
    DoctorId: 6,
    PatientId: 2,
    Symptoms: "Urinating often, Extreme fatigue",
  },
  {
    Id: 1016,
    title: "Adams",
    Disease: "Kidney disease",
    DoctorName: "Yara Barros",
    DepartmentName: "Diabetology",
    DepartmentId: 5,
    start: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 6,
      18,
      0
    ),
    end: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 6,
      18,
      30
    ),
    DoctorId: 6,
    PatientId: 3,
    Symptoms: "Decreased urine output",
  },
  {
    Id: 1017,
    title: "Janet",
    Disease: "Gastroparesis",
    DoctorName: "Amelia Edwards",
    DepartmentName: "Diabetology",
    DepartmentId: 5,
    start: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 2,
      14,
      0
    ),
    end: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 2,
      14,
      30
    ),
    DoctorId: 6,
    PatientId: 4,
    Symptoms: "Feeling cold",
  },
  {
    Id: 1018,
    title: "Laura",
    Disease: "Sleep apnea",
    DoctorName: "Amelia Edwards",
    DepartmentName: "Diabetology",
    DepartmentId: 5,
    start: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 4,
      12,
      0
    ),
    end: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 4,
      13,
      0
    ),
    DoctorId: 6,
    PatientId: 1,
    Symptoms: "Gasping for air during sleep",
  },
  {
    Id: 1019,
    title: "Milka",
    Disease: "Vision problems",
    DoctorName: "Amelia Edwards",
    DepartmentName: "Diabetology",
    DepartmentId: 5,
    start: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() - 2,
      10,
      0
    ),
    end: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() - 2,
      11,
      0
    ),
    DoctorId: 6,
    PatientId: 2,
    Symptoms: "Severe, sudden eye pain",
  },
  {
    Id: 1020,
    title: "Milka",
    Disease: "Feeling hungry after eating",
    DoctorName: "Paul Walker",
    DepartmentName: "Diabetology",
    DepartmentId: 5,
    start: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 2,
      12,
      0
    ),
    end: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 2,
      13,
      0
    ),
    DoctorId: 6,
    PatientId: 2,
    Symptoms: "Urinating often, Extreme fatigue",
  },
  {
    Id: 1021,
    title: "Adams",
    start: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 6,
      10,
      0
    ),
    end: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 6,
      11,
      0
    ),
    Disease: "Bone Fracture",
    DoctorName: "Amelia Edwards",
    DepartmentName: "Orthopedics",
    DepartmentId: 4,
    DoctorId: 5,
    PatientId: 3,
    Symptoms: "Swelling or bruising over a bone",
  },
  {
    Id: 1022,
    title: "Mercy",
    start: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate(),
      15,
      0
    ),
    end: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate(),
      15,
      30
    ),
    Disease: "Left Arm Fracture",
    DoctorName: "Yara Barros",
    DepartmentName: "Orthopedics",
    DepartmentId: 4,
    DoctorId: 5,
    PatientId: 5,
    Symptoms: "Deformity, such as a bent arm",
  },
  {
    Id: 1023,
    title: "Milka",
    Disease: "Rapid heartbeat",
    DoctorName: "Amelia Edwards",
    DepartmentName: "Cardiology",
    DepartmentId: 6,
    start: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() - 1,
      14,
      0
    ),
    end: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() - 1,
      14,
      30
    ),
    DoctorId: 7,
    PatientId: 2,
    Symptoms: "Fluttering sensation in the chest",
  },
  {
    Id: 1024,
    title: "Adams",
    Disease: "Lightheadedness",
    DoctorName: "Paul Walker",
    DepartmentName: "Cardiology",
    DepartmentId: 6,
    start: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 5,
      17,
      30
    ),
    end: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 5,
      18,
      30
    ),
    DoctorId: 7,
    PatientId: 3,
    Symptoms: "Sudden drop in blood pressure",
  },
  {
    Id: 1025,
    title: "Janet",
    Disease: "Shortness of breath",
    DoctorName: "Yara Barros",
    DepartmentName: "Cardiology",
    DepartmentId: 6,
    start: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 2,
      15,
      0
    ),
    end: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 2,
      15,
      30
    ),
    DoctorId: 7,
    PatientId: 4,
    Symptoms: "Nasal congestion, runny nose",
  },
  {
    Id: 1025,
    title: "Milka",
    Disease: "Chest pain or discomfort",
    DoctorName: "Amelia Edwards",
    DepartmentName: "Cardiology",
    DepartmentId: 6,
    start: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 3,
      17,
      0
    ),
    end: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 3,
      18,
      30
    ),
    DoctorId: 7,
    PatientId: 2,
    Symptoms: "Fast heart beat, and trouble breathing",
  },
  {
    Id: 1026,
    title: "Milka",
    Disease: "Racing heartbeat",
    DoctorName: "Amelia Edwards",
    DepartmentName: "Cardiology",
    DepartmentId: 6,
    start: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 6,
      15,
      30
    ),
    end: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 6,
      16,
      0
    ),
    DoctorId: 7,
    PatientId: 2,
    Symptoms: "A fluttering in your chest",
  },
  {
    Id: 1027,
    title: "Milka",
    Disease: "Heart Problem",
    DoctorName: "Amelia Edwards",
    DepartmentName: "Cardiology",
    DepartmentId: 6,
    start: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 3,
      14,
      0
    ),
    end: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() + 3,
      14,
      30
    ),
    DoctorId: 7,
    PatientId: 2,
    Symptoms: "Fluid buildup from being overweight",
  },
  {
    Id: 1028,
    title: "Milka",
    Disease: "Dizziness",
    DoctorName: "Paul Walker",
    DepartmentName: "Diabetology",
    DepartmentId: 5,
    start: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() - 1,
      19,
      0
    ),
    end: new Date(
      today.getFullYear(),
      today.getMonth(),
      today.getDate() - 1,
      19,
      30
    ),
    DoctorId: 6,
    PatientId: 2,
    Symptoms: "Feeling of lightheadedness or nearly fainting",
  },
];

export const specializationData = [
  {
    DepartmentId: 1,
    Id: "generalmedicine",
    Text: "General Medicine",
    Color: "#F538B2",
  },
  { DepartmentId: 2, Id: "neurology", Text: "Neurology", Color: "#33C7E8" },
  { DepartmentId: 3, Id: "dermatology", Text: "Dermatology", Color: "#916DE4" },
  { DepartmentId: 4, Id: "orthopedics", Text: "Orthopedics", Color: "#388CF5" },
  { DepartmentId: 5, Id: "Diabetology", Text: "Diabetology", Color: "#60F238" },
  { DepartmentId: 6, Id: "cardiology", Text: "Cardiology", Color: "#F29438" },
];

export const experienceData = [
  { Id: "1+ years", Text: "1+ years" },
  { Id: "2+ years", Text: "2+ years" },
  { Id: "5+ years", Text: "5+ years" },
  { Id: "10+ years", Text: "10+ years" },
  { Id: "15+ years", Text: "15+ years" },
  { Id: "20+ years", Text: "20+ years" },
];

export const dutyTimingsData = [
  { Id: "Shift1", Text: "08:00 AM - 05:00 PM" },
  { Id: "Shift2", Text: "10:00 AM - 07:00 PM" },
  { Id: "Shift3", Text: "12:00 AM - 09:00 PM" },
];

export const activityData = [
  {
    title: "Added New Doctor",
    Message: "Dr.Johnson James, Cardiologist",
    Time: "5 mins ago",
    Type: "doctor",
    ActivityTime: new Date(today.getFullYear(), 5, 8, 9, 0),
  },
  {
    title: "Added New Appointment",
    Message:
      "Laura for General Checkup on 7/3/2023, 4:00:00 PM with Dr.Molli Cobb",
    Time: "5 mins ago",
    Type: "appointment",
    ActivityTime: new Date(today.getFullYear(), 5, 8, 11, 0),
  },
  {
    title: "Added New Patient",
    Message: "James Richard for Fever and cold",
    Time: "5 mins ago",
    Type: "patient",
    ActivityTime: new Date(today.getFullYear(), 5, 8, 10, 0),
  },
  {
    title: "Added New Appointment",
    Message:
      "Joseph for consultation on 7/3/2023, 4:00:00 PM with Dr.Molli Cobb",
    Time: "5 mins ago",
    Type: "appointment",
    ActivityTime: new Date(today.getFullYear(), 5, 11, 11, 0),
  },
];

// Preference module data

export const timeSlots = [
  { Value: 10, Text: "10 mins" },
  { Value: 20, Text: "20 mins" },
  { Value: 30, Text: "30 mins" },
  { Value: 60, Text: "60 mins" },
  { Value: 120, Text: "120 mins" },
];

export const startHours = [
  { Value: "08:00", Text: "8:00 AM" },
  { Value: "09:00", Text: "9:00 AM" },
  { Value: "10:00", Text: "10:00 AM" },
  { Value: "11:00", Text: "11:00 AM" },
  { Value: "12:00", Text: "12:00 PM" },
];

export const endHours = [
  { Value: "16:00", Text: "4:00 PM" },
  { Value: "17:00", Text: "5:00 PM" },
  { Value: "18:00", Text: "6:00 PM" },
  { Value: "19:00", Text: "7:00 PM" },
  { Value: "20:00", Text: "8:00 PM" },
  { Value: "21:00", Text: "9:00 PM" },
];

export const views = [
  { Value: "Day", Text: "Daily" },
  { Value: "Week", Text: "Weekly" },
  { Value: "Month", Text: "Monthly" },
];

export const colorCategory = [
  { Value: "Departments", Text: "Department Colors" },
  { Value: "Doctors", Text: "Doctors Colors" },
];

export const bloodGroupData = [
  { Value: "AB+", Text: "AB+" },
  { Value: "A+", Text: "A+" },
  { Value: "B+", Text: "B+" },
  { Value: "O+", Text: "O+" },
  { Value: "AB-", Text: "AB-" },
  { Value: "A-", Text: "A-" },
  { Value: "B-", Text: "B-" },
  { Value: "O-", Text: "O-" },
];

export const dayOfWeekList = [
  { Value: 0, Text: "Sunday" },
  { Value: 1, Text: "Monday" },
  { Value: 2, Text: "Tuesday" },
  { Value: 3, Text: "Wednesday" },
  { Value: 4, Text: "Thursday" },
  { Value: 5, Text: "Friday" },
  { Value: 6, Text: "Saturday" },
];

// shift wise block data
export const shift1BlockData = [
  {
    Id: 50,
    title: "Off Work",
    start: new Date(today.getFullYear(), 5, 2, 17, 0),
    end: new Date(today.getFullYear(), 5, 2, 21, 0),
    RecurrenceRule: "FREQ=DAILY;INTERVAL=1;",
    IsAllDay: false,
    IsBlock: true,
    DoctorId: [1, 2, 3, 4, 5, 6, 7],
  },
];

export const shift2BlockData = [
  {
    Id: 51,
    title: "Off Work",
    start: new Date(today.getFullYear(), 5, 2, 8, 0),
    end: new Date(today.getFullYear(), 5, 2, 10, 0),
    RecurrenceRule: "FREQ=DAILY;INTERVAL=1;",
    IsAllDay: false,
    IsBlock: true,
    DoctorId: [1, 2, 3, 4, 5, 6, 7],
  },
  {
    Id: 52,
    title: "Off Work",
    start: new Date(today.getFullYear(), 5, 2, 19, 0),
    end: new Date(today.getFullYear(), 5, 2, 21, 0),
    RecurrenceRule: "FREQ=DAILY;INTERVAL=1;",
    IsAllDay: false,
    IsBlock: true,
    DoctorId: [1, 2, 3, 4, 5, 6, 7],
  },
];

export const shift3BlockData = [
  {
    Id: 53,
    title: "Off Work",
    start: new Date(today.getFullYear(), 5, 2, 8, 0),
    end: new Date(today.getFullYear(), 5, 2, 12, 0),
    RecurrenceRule: "FREQ=DAILY;INTERVAL=1;",
    IsAllDay: false,
    IsBlock: true,
    DoctorId: [1, 2, 3, 4, 5, 6, 7],
  },
];
